#:kivy 2.3.1

<Card>:
    size_hint: None, None
    size: 200, 300
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1 if self.is_hovered else 0  # Change color based on is_hovered
        RoundedRectangle:
            pos: self.center_x - self.width / 2 - 2, self.center_y - self.height / 2 - 2
            size: self.width + 4, self.height + 4
            radius: [20, 20, 20, 20]
    canvas:
        Color:
            rgba: (0.73, 0.32, 0.07, 1)
        RoundedRectangle:
            pos: self.center_x - self.width / 2, self.center_y - self.height / 2
            size: self.size
            radius: [20, 20, 20, 20]
        Color:
            rgba: (0, 0, 0, 1)
        RoundedRectangle:
            pos: self.center_x - self.width / 2 + 4, self.center_y - self.height / 2 + 4
            size: self.width - 8, self.height - 8
            radius: [18, 18, 18, 18]

<PlayArea>:
    size: 800, 360
    canvas:
        Color:
            rgba: (0.5, 0.5, 0.5, 1)
        Rectangle:
            pos: self.center_x - self.width / 2, self.center_y - self.height / 2
            size: self.size

<CardGame>:
    hand: hand
    play_area: play_area

    GridLayout:
        cols: 3
        rows: 3
        width: self.parent.width
        height: self.parent.height
        spacing: 8

        Widget:
            size_hint: None, None
            size: 200, 40
            canvas:
                Color:
                    rgba: (1, 0, 0, 1)
                Rectangle:
                    pos: self.pos
                    size: self.size
        
        Label:
            text: 'Card Game'
            font_size: 32
            color: (1, 1, 1, 1)
            size_hint: None, None
            size: 1086, 40
            pos_hint: {'center_x': 0.5, 'y': 0.9}
            canvas.before:
                Color:
                    rgba: (0, 1, 0, 1)
                Rectangle:
                    pos: self.pos
                    size: self.size
        
        Button:
            text: 'Menu'
            size_hint: None, None
            size: 200, 40
        
        Widget:
            size_hint: None, None
            size: 200, 544
            canvas:
                Color:
                    rgba: (0, 0, 1, 1)
                Rectangle:
                    pos: self.pos
                    size: self.size
        
        PlayArea:
            id: play_area

        Widget:
            size_hint: None, None
            size: 200, 544
            canvas:
                Color:
                    rgba: (1, 0, 1, 1)
                Rectangle:
                    pos: self.pos
                    size: self.size
        
        Widget:
            size_hint: None, None
            size: 200, 300
            canvas:
                Color:
                    rgba: (1, 1, 0, 1)
                Rectangle:
                    pos: self.pos
                    size: self.size
        
        Hand:
            id: hand
            size_hint: None, None
            width: self.minimum_width
            height: 300
            orientation: 'horizontal'
            spacing: 8

        Widget:
            size_hint: None, None
            size: 200, 300
            canvas:
                Color:
                    rgba: (0, 1, 1, 1)
                Rectangle:
                    pos: self.pos
                    size: self.size

